### ISSUE TITLE
Event modal button height is low

### ISSUE THREAD

**Issue by hanuz06** [nibdo/kalend#100]
There are 2 problems:

1) Each day shows only 1 event. If I have 2 events I can't see the second one.
2) When click on event a modal pops up. The height of button is low as I can't see the text properly.

![image](https://user-images.githubusercontent.com/17211293/149896296-73bde6c4-e034-404f-a9ad-413bb8c14906.png)

![image](https://user-images.githubusercontent.com/17211293/149895780-4ae372e2-c9ca-4bcc-a74a-5bcd4559cea6.png)

**Comment by nibdo** [comment]
Hello, thank you, I see the problem and I will look into it.

**Comment by nibdo** [comment]
Hello, first problem should be fixed in version 0.7.1, second one should be fixed later in the future release.

**Comment by hanuz06** [comment]
Okay. Thank you buddy.

**Comment by nibdo** [comment]
Should be improved in version 0.7.2
