### ISSUE TITLE
reacti18next translations lost on Kalend component render

### ISSUE THREAD

**Issue by rparmasar** [nibdo/kalend#103]
Hello,

I'm currently using the `Kalend` component in my react application that also uses react-i18next for localization. The issue is that before the `Kalend` component is rendered, the translations work fine e.g.
![Screen Shot 2022-01-18 at 4 00 43 PM](https://user-images.githubusercontent.com/58739790/150017945-90de34f2-f505-4e01-97e7-4dec96f052b8.png)

However when the `Kalend` component is rendered on screen for the first time, the translations stop working and are displayed as their keys instead e.g.
![Screen Shot 2022-01-18 at 4 01 50 PM](https://user-images.githubusercontent.com/58739790/150018083-10ba64e9-23b0-4b25-b52e-e2141a2c0e54.png)

Here is my `Kalend` component set-up:
```
<Kalend
    events={marginScoreEvents}
    initialDate={`${marginScores[0].day}T20:00:00.000Z`}
    hourHeight={60}
    initialView={CalendarView.MONTH}
    disabledViews={[CalendarView.DAY, CalendarView.WEEK, CalendarView.YEAR, CalendarView.AGENDA]}
    timeFormat={'24'}
    weekDayStart={'Monday'}
/>
```

Any help is much appreciated! Let me know if you need more information, thank you!

# Update
I think what's happening is that the `i18n` instance in the `Kalend` component is overriding my instance of `i18n` thus my namespaces aren't being recognized. Not sure how to fix but will post a solution if I find one.

**Comment by rparmasar** [comment]
# Update
So I think when the `Kalend` component first renders, it is interfering with loading of the namespaces for the translations thus the `t` function can't resolve the keys

**Comment by nibdo** [comment]
Hello, sorry for problems. As this was discussed here https://github.com/nibdo/kalend/issues/95 , I will refactor translations to some simple parser, so this won't be problem then. 

So this should solve your problem. I have something in progress and I will let you know, when update is ready.

**Comment by rparmasar** [comment]
Hey @nibdo, no worries. I managed to solve it by explicity setting the instance of `i18n` i'm using by wrapping my `App` component in the `I18nextProvider` component.
```
<I18nextProvider i18n={i18n}>
    <App />
</I18nextProvider>
```

More reading here for anyone encountering this issue: https://react.i18next.com/latest/i18nextprovider

**Comment by nibdo** [comment]
That's great, might be useful for someone with same problem in the future.
