### ISSUE TITLE
Resizing browser window throws error

### ISSUE THREAD

**Issue by bruceharrison1984** [nibdo/kalend#109]
**Describe the bug**
Resizing the browser window while Kalend is visible throws an error.
`TypeError: Cannot read properties of undefined (reading 'length')`
Refreshing the page restores it to working order, until you resize the window again.

**Expected behavior**
The window should resize without causing Kalend to crash.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by nibdo** [comment]
Thank you. Should be fixed in 0.7.4 with some other small improvements.
