### ISSUE TITLE
Kalend usage

### ISSUE THREAD

**Issue by 334rashad** [nibdo/kalend#111]
Hi, I am trying to implement this calendar in my project. It looks nice and I like the features but I'm having some troubles which I can't find out why. The calendar "table"(or timetable) doesn't show at all but I can see on the web developer tools that it is there. I attached the picture how calendar is shown on my page. Could you please help with advice, maybe there is an obvious mistake that I cannot see? This is the part of the code for calendar:

const eventss = [
        {
            id: 1,
            startAt: '2021-12-21T18:00:00.000Z',
            endAt: '2021-12-21T19:00:00.000Z',
            timezoneStartAt: 'Europe/Berlin', // optional
            summary: 'test',
            color: 'blue',
//             calendarID: 'work'
        },
        {
            id: 2,
            startAt: '2021-12-21T15:00:00.000Z',
            endAt: '2021-12-21T16:00:00.000Z',
            timezoneStartAt: 'Europe/Berlin', // optional
            summary: 'test1',
            color: 'blue'
        },
        {
            id: 3,
            startAt: '2022-01-25T14:00:00.000Z',
            endAt: '2022-01-25T15:00:00.000Z',
            timezoneStartAt: 'Europe/Berlin', // optional
            summary: 'test2',
            color: 'blue',
        },
        {
            id: 4,
            startAt: '2021-12-21T11:00:00.000Z',
            endAt: '2021-12-21T13:00:00.000Z',
            timezoneStartAt: 'Europe/Berlin', // optional
            summary: 'test3',
            color: 'blue'
        }
    ]

return (
            <Kalend
//               onEventClick={onEventClickData}
//               onNewEventClick={onNewEventClick}
              events={eventss}
              initialDate={new Date().toISOString()}
              hourHeight={60}
              initialView={CalendarView.WEEK}
              disabledViews={[CalendarView.DAY]}
//               onSelectView={onSelectView}
//               selectedView={selectedView}
//               onPageChange={onPageChange}
              timeFormat={'24'}
              weekDayStart={'Monday'}
//               calendarIDsHidden={['work']}
              language={'en'} />
        );

![Screenshot from 2022-01-26 11-13-10](https://user-images.githubusercontent.com/32520427/151145167-86a9488e-93cf-466a-8662-79b136996c95.png)

**Comment by 334rashad** [comment]
I was working on this issue and the fix comes when i change the height from 100% to fixed px in css class "Kalend__Calendar__root Kalend__main". Then timetable becomes visible. Is there anything I could do to fix this without changing root css?

**Comment by nibdo** [comment]
Hello, currently this works like this: Kalend tries to occupy 100% of it's parent container, so you have to set something to parent (be it body, or some other element). You don't need to use fixed height for that parent element, but check if it is expanded like you want.

For example if you have html and body set to 100% height, Kalend will fit whole screen. It might not be the most intuitive, but I haven't found better way yet.

**Comment by 334rashad** [comment]
Thanks for the reply. Yes I wrapped it with parent container and now it works. The parent container has fixed height. When i put parent height in % it doesn't work. Maybe I am doing something wrong idk, but it works. Thanks
