### ISSUE TITLE
Name of the month in header gets stuck

### ISSUE THREAD

**Issue by 334rashad** [nibdo/kalend#112]
When I change the view from week to month or any other view the calendar gets updated to today, but the name of the month and year show old data. You can see it in the pictures.

![Screenshot from 2022-01-26 14-57-01](https://user-images.githubusercontent.com/32520427/151176770-6703d856-1b0c-40dc-ad82-2732fa898577.png)

![Screenshot from 2022-01-26 14-57-27](https://user-images.githubusercontent.com/32520427/151176792-37efd8b8-83af-4e1c-94fb-702f27cbb293.png)

**Comment by nibdo** [comment]
Thank you for report, this should be fixed in 0.7.5
