### ISSUE TITLE
Doesn't work with Next js

### ISSUE THREAD

**Issue by Mazahir26** [nibdo/kalend#120]
**Describe the bug**
I installed kalend, but when I run the app it gives me an error 'Invalid 'main' field in '...project\node_modules\kalend-layout\package.json' of 'dist/main.js'. Please either fix that or report it to the module author'

**To Reproduce**
1. Create a Next js project
2.  Install Kalend 
3.  add the component in the index.ts or index,js, run the app.
4.  See error

**Expected behavior**
I am using next js with typescript template. I think that it should have worked out of the box without any trouble shooting.

**Screenshots**
![Screenshot 2022-02-05 211852](https://user-images.githubusercontent.com/46394948/152648765-da158dcc-c4ec-4b1d-b2ff-36828c6962c7.png)
![Screenshot 2022-02-05 212054](https://user-images.githubusercontent.com/46394948/152648767-1ae8a614-a39b-48c5-a11e-944f661c60b8.png)

**Desktop **
 - OS: windows 11
 - Browser: Brave
 - Version: 1.35.100

**Edit**
Its not the error of this package but one of the helper packages [kalend-layout](https://github.com/nibdo/kalend-layout).

**Comment by nibdo** [comment]
Hello, that kalend-layout should be unrelated warning.  

Issue here is that Kalend relies on document, which is problem for SSR, so you have to adjust little bit your import.
 
Modifying import like this should be enough:
`const KalendComponent = dynamic(() => import('kalend'), { ssr: false })`

**Comment by Mazahir26** [comment]
> Hello, that kalend-layout should be unrelated warning.
> 
> Issue here is that Kalend relies on document, which is problem for SSR, so you have to adjust little bit your import.
> 
> Modifying import like this should be enough: `const KalendComponent = dynamic(() => import('kalend'), { ssr: false })`

Hey, thanks for the reply, Your solution works.
I understood the problem and found an alternate solution.
You can use useEffect hook to set the loading state to false and use conditional rendering to render the Kalend Component.
`const [loading, setLoading] = useState(true);
  useEffect(() => {
    setLoading(false);
  });`

something like this.
`{loading ? (
        <Spinner
          thickness="4px"
          speed="0.65s"
          emptyColor="gray.200"
          color="blue.500"
          size="xl"
        />
      ) : (
        <Kalend initialView={CalendarView.WEEK} events={events} />
      )}`

or You can use @nibdo solution as well :).

Thank you so much @nibdo for helping me out.
