### ISSUE TITLE
HourHeight not resizing dynamically

### ISSUE THREAD

**Issue by Aikoze** [nibdo/kalend#123]
Hi everybody,

First of all , this lib is very nice.

**Bug description**

I have an issue about changing the `hourHeight`, when doing this dynamically, we are not seeing the good result on the screen. We need to change the width of the component to see events resizing happening.

You can easily reproduce this comportment when resizing your window.

**Expected behavior**

I want to let the user change the `hourHeight` by himself with a hook linked to the property and dynamically see the result

**Comment by nibdo** [comment]
Hello, thank you, I will check it.

**Comment by nibdo** [comment]
Should be fixed in version 0.9.6 -> listener for change in prop hourHeight will rerender events for correct result.
