### ISSUE TITLE
disabledViews doesn't work on example_app, nor for my own app.

### ISSUE THREAD

**Issue by williamchenghu** [nibdo/kalend#132]
**Describe the bug**
`disabledViews` doesn't seem working for example_app, neither would it work on my own app.

**To Reproduce**
1. Go to 'example_app' directory under the repo
2. `npm i`
3. `npm start`
4. pass a couple `CalendarView` choices to the `disabledViews` array, for this case `CalendarView.DAY` and `CalendarView.MONTH`: 
```javascript
disabledViews={[CalendarView.DAY, CalendarView.MONTH]}
```

**Expected behavior**
calendar view choices will filter out those disabled ones, for this case I shouldn't be able to see 'Day' or 'Month' anymore.

**Screenshots**
<img width="448" alt="Screenshot 2022-03-15 at 22 36 08" src="https://user-images.githubusercontent.com/4009417/158468323-ba51f7a2-1048-4a80-a28a-c3e83df200f9.png">
<img width="318" alt="Screenshot 2022-03-15 at 22 36 17" src="https://user-images.githubusercontent.com/4009417/158468330-a4e2f627-78a7-408f-954d-2f32ecd2e7de.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: macOS: 12.3, Chrome: 99.0.4844.74

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
- N/A

**Comment by vyamashiro** [comment]
related to #133

**Comment by nibdo** [comment]
Fixed in 0.9.9, thanks to @vyamashiro
