### ISSUE TITLE
Focused hours range / time point (at week / day(s) view)

### ISSUE THREAD

**Issue by williamchenghu** [nibdo/kalend#146]
**Is your feature request related to a problem? Please describe.**
For some use cases, it may not make that much sense to one to see those blank hours outside their application interest. (e.g., 18:00 - 7:00).

**Describe the solution you'd like**
**As a** regular user of the library, **I'd like to** have a props to define working hours range at my choice, **so that** the viewport always focus to show defined hour range at higher priority (probably still need to let end users to scroll to view those less-interest time ranges).

**Describe alternatives you've considered**
Perhaps a props allow developer to choose the time range isn't always necessary. If a "focus time point" can be defined by developer would still be awesome. For instance, if I can choose 12:00 at noon as the "focus time point", then it's up to the browser's view height to determine how big of a time range can be displayed (ex. maybe bigger screen / high resolution can show +/- 8h where smaller screen can still show +/- 4h.).

**Additional context**
It be a bonus if elsewhere than the "preferred time range" can be shaded.

**Comment by nibdo** [comment]
Hello @williamchenghu,

this is interesting idea. 

I was already wanting to add missing functionality for focusing to current time, so this might be two in one. Alternatively, adding also option to show only defined working hours could be nice too, though that change would take some time.

**Comment by nibdo** [comment]
Hi @williamchenghu, so far I have added scroll to current hour in latest version with option to focus to custom hour with prop **focusHour**.

**Comment by williamchenghu** [comment]
Wow that's swift! I'll go check them out! Thank you so much!
