### ISSUE TITLE
The initialDate parameter has no effect

### ISSUE THREAD

**Issue by IvanSavoskin** [nibdo/kalend#150]
**Describe the bug**
The `initialDate` parameter has no effect

**To Reproduce**
1. Set `initialDate` to a value other than the current day, for example `2021-12-26T06:00:00Z`
2. When rendering, today's date is displayed in the calendar

**Expected behavior**
The calendar is rendered on the number specified in the `initialDate` parameter

**Desktop:**
 - OS: macOS 12.3
 - Browser: Chrome 100.0.4896.75 
 - Kalend Version: 0.11.2

**Comment by nibdo** [comment]
Thank you, should be fixed in 0.12.0
