### ISSUE TITLE
Show week numbers on the side

### ISSUE THREAD

**Issue by yatki** [nibdo/kalend#152]
**Describe the solution you'd like**
Hey, thank you very much for the great work. Would be nice to have week numbers on the side as google calendar has on the monthly view. 

Would you consider adding it to your component?

![image](https://user-images.githubusercontent.com/26697004/163321268-65a1b058-f1e7-47a9-818a-45f87a83cc79.png)

**Comment by nibdo** [comment]
Hello, thank you for suggestion, you can try it in version 0.12.0 with prop showWeekNumbers.
