### ISSUE TITLE
Autoscroll after rendering events since version 0.12.0

### ISSUE THREAD

**Issue by tarapiygin** [nibdo/kalend#158]
**Describe the bug**
After updating the event styles from version 0.11.0 to version 0.13.0, the calendar auto-scrolls, which creates problems for using it for embedding in a page.

**To Reproduce**
1. Add a calendar along with other elements to the page
2. After rendering the calendar, an auto-scroll to the event elements will occur

**Expected behavior**
Prior to version 0.12.0, auto-scroll did not appear

**Desktop:**
 - OS: Windows 11
 - Browser: Сhrome
 - Version: 100

**Smartphone:**
 - Device: Phone13, Google Pixel 6
 - OS: IOS, android
 - Browser safari, chrome

**Comment by nibdo** [comment]
Hi, sorry for inconvenience, I have made auto scrolling optional in new version 0.13.1.

**Comment by tarapiygin** [comment]
Thank you!
It's great that you fixed the problem so quickly.
