### ISSUE TITLE
time-picking click being recognized as 'onMouseUp' randomly

### ISSUE THREAD

**Issue by williamchenghu** [nibdo/kalend#164]
**Describe the bug**
When user is clicking on a time slot, instead of being recognized as "point" clicking, sometime it will be `onMouseUp` (same as "drag define time range") which affects the event creation dialogue submission. (somehow this feels like it's too "sensitive" to be recognized as a "range selection")

**To Reproduce**
1. Go to weekly calendar view
2. Click on any preferred point for time picking
3. if you click very light and rapid (e.g., tap on the trackpad), the event will be recognized as `onClick`
4. if you click relatively moderate and/or sloppy (e.g., click hard through 2nd haptic feedback on mac trackpad), the event will be recognized as `onMouseUp`.
5. Once it's being recognized as `onMouseUp`, any evasion / interruption on the event creation procedure will stuck the user with some "left-hanging" states (e.g., `startAt`, `endAt`), see issue #163 for further details. (additionally, probably due to the "selected time range" is too small, `startAt` and `endAt` freaks out and always show as `undefined`)

**Expected behavior**
Could there be some way to "tune down" the sensitivity between `onClick` and `onMouseUp`? (maybe a very tiny ms delay can be the threshold?)

**Screenshots**
![Screenshot 2022-04-27 at 14 58 42](https://user-images.githubusercontent.com/4009417/165515779-565b9a28-6320-4128-a717-8d83f559a719.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Browser Chrome
 - Version 101.0.4951.41 (Official Build) (arm64)

**Additional context**
-

**Comment by williamchenghu** [comment]
As a matter of fact, my bug report was based on kalend version 0.12.1. As I just updated to 0.14.1, either this bug isn't valid anymore or I have not been able to trigger it so far.
Wonder which specific part within the updates could've patched this?

**Comment by nibdo** [comment]
Hi @williamchenghu, thanks for the report, I think it might be fixed in 0.13.0 where few parts for events were refactored.
