### ISSUE TITLE
Enable event view to be pluggable

### ISSUE THREAD

**Issue by cazfletch** [nibdo/kalend#176]
Similar to a custom header. Provide a way to have custom events. Its great that you can now add styling to events but it would be really great if you can have a custom event. This would allow for things like adding a context menu to an event rather than only being able to say what happens when you click on the event, or add buttons to an event for doing whatever you want when you click the button

**Comment by nibdo** [comment]
I am open to ideas how this should be handled.

The best would be just adding some children prop to event which will render in the internal (blank) event container.

**Comment by cazfletch** [comment]
Adding a children prop to the event sounds good.

**Comment by nibdo** [comment]
I played little bit with this idea, and as concept, it is working fine with custom texts, buttons, etc. 

I have just few concerns, how to do this right.

1. Might be problematic to tune this right for dragging events.
2. It might need custom adjustments for different views like agenda, week or month view. Each view would be able to fit and use different information, with agenda as the most forgiving and month the least.
3. If you want to add for example button, which will have critical function, you have to be sure, that it will be always visible and not cut by too short event. This could be solved by setting minimal event height, but it might disrupt "realism" of calendar table. 
![custom1](https://user-images.githubusercontent.com/57879411/174893701-ac1e6863-61dc-4cf9-8c90-c7f9675b443c.png)

**Comment by cazfletch** [comment]
Maybe you could display a different custom component for each of the different views, and if you don't supply one it just gives you the default one. Agenda view looks very different to the other ones so i can imagine you would want a different custom component for this especially.

I think it would up to the user to make sure that the component they supplied worked with short events. You could document that this needs to be taken into consideration.

**Comment by nibdo** [comment]
Added in 0.15.0
