### ISSUE TITLE
Events that cross midnight are treated as all day events even if they are less than 24 hours

### ISSUE THREAD

**Issue by cazfletch** [nibdo/kalend#177]
**Describe the bug**
When you have an event that goes across midnight it is treated as an all day event.  Only events longer than 24 hours should be treated as all day events. If it is less than 24hours it should appear as a normal event. It should also display all day events in the day view.

**To Reproduce**
Add an event that starts at 10pm and finishes at 3am

**Expected behaviour**
I would expect the event to still appear in the day view 

**Screen shots**
This is what i would expect it to look like in day view 
![image](https://user-images.githubusercontent.com/23044145/172900312-dd772ca1-77da-4f49-a289-b636bc371b07.png)

The above screenshot is how google calendar shows it

**Comment by cazfletch** [comment]
I started adding a fix here https://github.com/nibdo/kalend-layout/pull/9

**Comment by nibdo** [comment]
Hello, thank you, I will check it and let you know.

**Comment by nibdo** [comment]
Added to new version, thank you again. 

If you will like and want it, I would like to have you listed as contributor also here on main repo, so feel free to make some pull request with empty edit of readme for example :)

**Comment by cazfletch** [comment]
Thanks for fixing :). Could you also make all day events appear on the day view please?

**Comment by nibdo** [comment]
Of course, they should be visible now.

**Comment by cazfletch** [comment]
can confirm this is now fixed, thanx so much
