### ISSUE TITLE
showWeekNumbers gives error

### ISSUE THREAD

**Issue by Philip2809** [nibdo/kalend#179]
Hello!

When setting the "showWeekNumbers" prop to true I get this error:
`Warning: Each child in a list should have a unique "key" prop.`
Could you add a key prop to the child to remove this error? I might believe this is something new in react.

Also awesome repo, love it, but might be good to explain to set the height value to something for things to show up. I just spent about and hour trying to figure out what was wrong until I saw an old issue about it.

**Comment by nibdo** [comment]
Hello, this should be fixed now. Sorry for problems and thanks for suggestion, I will add it somewhere more visible.
