### ISSUE TITLE
Contributing helper script

### ISSUE THREAD

**Issue by cazfletch** [nibdo/kalend#181]
When i tried to follow the contributing instructions in the documentation i just kept getting an error saying the hooks cannot be used outside of react. It would be really helpful to provide a script in the example app that you can run and it sets up the npm linking for you. Maybe there could be a flag for first time setup and a flag for when you have made changes to the calendar component.

**Comment by nibdo** [comment]
Yes, it is still not ideal and I would like to find some better and quicker way for development. I think Gulp was little bit faster for development build process.

I am using this from kalend main folder:

` npm i --force && npm run build && npm link
`

and this from example_app folder 
```

rm -r -f /YOUR_PATH/kalend/node_modules/react-dom
rm -r -f /YOUR_PATH/kalend/node_modules/react

npm link kalend --force
```

I will prepare some universal script from it.

**Comment by yc-codes** [comment]
Any update on this?

**Comment by nibdo** [comment]
Added to documentation https://docs.kalend.org/docs/basics/developing
