### ISSUE TITLE
Testing with jest and react testing library fails 

### ISSUE THREAD

**Issue by sstteewwaarrtt** [nibdo/kalend#182]
Trying to render kalend with jest and react testing library results in the following error:

`[Calend]: CSS file not imported.
             Reason: You probably forgot to import css file in your app as
             import 'kalend/dist/styles/index.css';

             Valid usage:
             import Kalend from 'kalend';
             import `'kalend/dist/styles/index.css';`

The css file is definitely imported and everything renders fine in the actual app.

**Comment by nibdo** [comment]
Hi, I assume this occurred because in testing library you didn't have "window" like in browser, so it could not find styling applied.
I have added prop "testMode" in 0.14.14, which while set to "true" will disable this validation.
