### ISSUE TITLE
Beta testing: Custom event components

### ISSUE THREAD

**Issue by nibdo** [nibdo/kalend#184]
Hello, I have published first beta version with custom event components as was mentioned here https://github.com/nibdo/kalend/issues/176

Would like to hear your feedback about functionality or bugs.

**Latest beta version: [0.15.0-beta.0](https://www.npmjs.com/package/kalend/v/0.15.0-beta.0)**

Example how to add components to event:
https://github.com/nibdo/kalend/blob/release/0.15.0/example_app/src/utils/helper.tsx

Custom event components:
https://github.com/nibdo/kalend/blob/release/0.15.0/example_app/src/components/Event.tsx

**Known bugs:**

- [x] Click event on custom button in x-days view is propagating to parent component

**Comment by cazfletch** [comment]
Had a quick play and it looks great :)

**Comment by nibdo** [comment]
Great, thank you :)

**Comment by nibdo** [comment]
Thanks @gobsej,

it is meant for custom clickable surfaces, like buttons or menu buttons inside event. So for example when you click on menu in event component, it will also open that event, because click is propagated further - which is not desired.
