### ISSUE TITLE
Vite: Failed to resolve entry for package "kalend"

### ISSUE THREAD

**Issue by mJR-exe** [nibdo/kalend#194]
**Describe the bug**
The bug happens when I run the `yarn vite` command

**Screenshots**
![image](https://user-images.githubusercontent.com/61773084/181353530-875f7b20-c121-4308-8c59-8e301370214d.png)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version 103.0

The `"main"` declaration that is in the `package.json` is with the `main.js` file, which is not present in the dependency folder.
![image](https://user-images.githubusercontent.com/61773084/181354859-451f07f6-806f-4cd6-9cef-b9537e35c783.png)

**Comment by nibdo** [comment]
Fixed in 0.15.2
