### ISSUE TITLE
How to full day single day events?

### ISSUE THREAD

**Issue by yss14** [nibdo/kalend#195]
Thanks for this awesome library!

How can I realize full day events which span only a single day (e.g. a birthday).

```typescript
{
    id: 3,
    startAt: "2022-07-28T00:00:00.000Z",
    endAt: "2022-07-28T23:59:59.999Z",
    timezoneStartAt: "UTC",
    timezoneEndAt: "UTC",
    summary: "Whole day",
    color: "blue",
}
```

results in a full span calendar event for that day and not a sticky element at the top.

![Screenshot 2022-07-28 at 14 23 57](https://user-images.githubusercontent.com/4346842/181504152-753e5bbc-120c-4fde-ae6e-a9f911b24262.png)

When I change `endAt` to `2022-07-29T00:00:00.000Z` the event is displayed sticky at the top, but now spans 2 days.

![Screenshot 2022-07-28 at 14 23 38](https://user-images.githubusercontent.com/4346842/181504182-f95098d2-eda6-459e-b015-7f65ed9d666d.png)

Is there any way to setup a single full day calendar event like google calendar supports it?
![Screenshot 2022-07-28 at 14 26 03](https://user-images.githubusercontent.com/4346842/181504616-1b05c916-c58e-441b-8da0-3b4210e7f987.png)

**Comment by nibdo** [comment]
Hello, you can just set **allDay: true** in event object.

**Comment by yss14** [comment]
Thanks!
