### ISSUE TITLE
Initial view month calendar is not rendered

### ISSUE THREAD

**Issue by yss14** [nibdo/kalend#196]
**Describe the bug**
Kalend with `initialView=CalendarView.MONTH` does not display calendar with events. Only on the second render, e.g. after some action or event-refetching the month calendar view is rendered correctly.

**To Reproduce**

[Here](https://codesandbox.io/s/trusting-resonance-ncdd8f?file=/src/App.tsx:1863-1881) is a codesandbox with the bug.

```typescript
const eventsSimple: CalendarEvent[] = [
  {
    id: 1,
    startAt: "2022-08-25T14:00:00.000Z",
    endAt: "2022-08-25T16:00:00.000Z",
    timezoneStartAt: "Europe/Berlin",
    timezoneEndAt: "Europe/Berlin",
    summary: "14-16 Uhr",
    color: "orange",
    calendarID: "simple"
  },
  {
    id: 2,
    startAt: "2022-07-27T15:00:00.000Z",
    endAt: "2022-07-27T17:00:00.000Z",
    timezoneStartAt: "Europe/Berlin",
    timezoneEndAt: "Europe/Berlin",
    summary: "15-17 Uhr",
    color: "blue",
    calendarID: "simple"
  }
];

<Kalend
  onEventClick={(event) => console.log(event)}
  events={eventsSimple}
  initialDate={new Date().toISOString()}
  hourHeight={60}
  initialView={CalendarView.MONTH}
  disabledViews={[CalendarView.AGENDA, CalendarView.THREE_DAYS]}
  timeFormat={"24"}
  weekDayStart={"Monday"}
  language={"en"}
/>
```

**Expected behavior**
Month calendar view should be displayed at the first render.

**Screenshots**
![Screenshot 2022-08-01 at 08 46 21](https://user-images.githubusercontent.com/4346842/182089516-a6e15a8d-d4c0-47e3-8234-0e285ffb1c9f.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chromium
 - Version: 94.0.4606.71

**Additional context**
- `kalend@0.15.1`

**Comment by nibdo** [comment]
### This is problem, when there is no fixed height value in some parent element (vh, or some px value for example). If you use just 100% height, at the moment of first render Kalend doesn't recognize height of parent and can't render content.

That's why on some next action it is corrected, because then it has access to height of the parent container.

I have not yet found better way, how to make this simpler while keeping required responsiveness for different use cases.

**Comment by yss14** [comment]
@nibdo Thanks for the explanation, makes sense. I will close this issue since it seems not like a bug then.
