### ISSUE TITLE
Long schedules don't show what date/time they start and stop

### ISSUE THREAD

**Issue by cazfletch** [nibdo/kalend#200]
When you create a long schedule it doesn't have any of the date or time information on it.

**Comment by nibdo** [comment]
Hi, sorry, I am not sure if I understand this issue, what do you mean by long schedule?

**Comment by cazfletch** [comment]
Sorry I meant for schedules that go over 24 hours so become all day schedules

**Comment by nibdo** [comment]
You mean event box doesn't show this text, when it is placed as all day event in header? If yes, this is intentionally due to space restrictions.

**Comment by cazfletch** [comment]
Yes that’s what I meant. Ok will close
