### ISSUE TITLE
Clicking on an hour line can result in new event not being fired

### ISSUE THREAD

**Issue by cazfletch** [nibdo/kalend#205]
If you click exactly on an hour line and don't drag then the new event click event is not always fired

**Comment by nibdo** [comment]
I was not able to replicate this issue. But another problem with hour line was fixed in new version, so might be worth to check it. What browser did you use?

**Comment by cazfletch** [comment]
I was using chrome. I will update to the latest version and check if it’s fixed

**Comment by cazfletch** [comment]
@nibdo I have tried the latest version and i can make this happen still

**Comment by nibdo** [comment]
I think I found it, should be fixed in 0.15.4
