### ISSUE TITLE
Console error when creating an event by dragging

### ISSUE THREAD

**Issue by Kurler3** [nibdo/kalend#230]
**Description**
I'm trying to use Kalend in a react project and after creating an event by dragging instead of just clicking I get this error

![image](https://user-images.githubusercontent.com/43253459/188166495-8f80a574-df30-4969-b293-b546a271932a.png)

**Desktop:**
 - Windows
 - Chrome

**Comment by nibdo** [comment]
Hello, would you be please able to recreate this bug in something like codepen? Or maybe provide more details under which conditions it occurs so I could simulate it? 

Finding where this value is will be easy, but I have not experienced this issue, so this could be quite hard to debug.

**Comment by Kurler3** [comment]
We can create events by either just left clicking once (defaults to 1 hour difference between the start and end date) or we can left-click and hold and choose a different end time. This issue happens when creating an event with the second option. 
I would try to recreate in codepen but it's really just this holding way of creating an event that is making this bug happen

**Comment by jianhao2010303** [comment]
I encountered the same problem, and I have turned off drag creation.

**Comment by aaron-hutton** [comment]
Doing some testing of the library and I've been able to reproduce this fairly consistently. It occurs even just when just calling the component with `<Kalend events={[]} />`

You have to first drag up to create a new event with an end time but variable start time. Finish the drag and the event disappears, then click and drag on the blank space where the event was. It only seems to happen once per page load though.

**Comment by nibdo** [comment]
Thank you. This should be fixed in version 0.17.6.
