### ISSUE TITLE
Drag and drop week view

### ISSUE THREAD

**Issue by nibdo** [nibdo/kalend#25]

**Comment by nibdo** [comment]
Merged to development

**Comment by nibdo** [comment]
Hello, I have published version 0.2.0. with support for dragging events, but there is one problem about dragging with "touch" movement f.e. on mobile devices where both parent app/page and Kalend calendar table are scrolling during dragging and touching. I have not yet found cross browser solution. 

- obvious way by setting overflow: hidden is not helping as it hides scrollbar and messes with width,
- ignoring scrolling with event listeners is not great for cross browser support,
- setting position: fixed on html/body during dragging is problematic as this is just component for other apps and this would be probably possible only putting component to iframe

I wil try to investigate it little more and maybe somebody would have better idea. Thank you

**Comment by Eragaus** [comment]
Did you try to get the cursor position when dragging an event? If the cursor is a specific position, the scroll could be automatic.
I don't know it is possible. It's just an idea.

**Comment by kkatsi** [comment]
It would be useful. in my opinion. to add a simple way, like using a prop, to disable drag n drop feature, until you find a fix. Thanks!

**Comment by nibdo** [comment]
Disabled for now for touch events since version 0.6.0
