### ISSUE TITLE
Calendar table is not visible. What am I missing?

### ISSUE THREAD

**Issue by f3dd3rn** [nibdo/kalend#63]
Hi!
Quick question:
Events within a day aren't visible. There seems to be something wrong with the set height (it is 0).
What am I missing here to get the calendar to work?

Thank you in advance for your help. :)

**Comment by nibdo** [comment]
Hello, can you please attach screenshot how does it look like for you?

Also check if parent element where Kalend is placed has some width, height dimensions set. Thank you
