### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by kkatsi** [nibdo/kalend#83]
I'm trying to import a custom local json including translations in greek language this way:

```
import gr from 'gr.json'

<Kalend
...
customLanguage={gr}
/>
```

my json is formatted as the existed jsons for the supported languages but in greek like this:

```
{
  "buttons": {
    "today": "Σήμερα",
    "agenda": "Ατζέντα",
    "day": "Ημέρα",
    "threeDays": "3ήμερο",
    "week": "Εβδομάδα",
    "month": "Μήνας",
    "showMore": "Περισσότερα"
  },
  "months": {
    "january": "Ιανουάριος",
    "february": "Φεβρουάριος",
    "march": "Μάρτιος",
    "april": "Απρίλιος",
    "may": "Μάιος",
    "june": "Ιούνιος",
    "july": "Ιούλιος",
    "august": "Αύγυοστος",
    "september": "Σεπτέμβριος",
    "october": "Οκτώβριος",
    "november": "Νοέμβριος",
    "december": "Δεκέμβριος"
  },
  "weekDays": {
    "Mon": "Δευ",
    "Tue": "Τρί",
    "Wed": "Τετ",
    "Thu": "Πέμ",
    "Fri": "Παρ",
    "Sat": "Σάβ",
    "Sun": "Κυρ"
  }
}
```

However Kalend is still displayed in English and nothing changes. When tried to change to one of the already supported languages like 'es' it works properly as expected. Am i missing something? 

Thanks in advance

**Comment by nibdo** [comment]
Hello, sorry, I missed one setting in example, I will update it.

You need also set language property to "customLanguage", so it would look like this:
```
        language={'customLanguage'}
        customLanguage={gr} 
```

**Comment by kkatsi** [comment]
Thanks! It worked!

**Comment by nibdo** [comment]
Great :) Thank you for finding this
