### ISSUE TITLE
Kalend not showing properly

### ISSUE THREAD

**Issue by slawomirdur** [nibdo/kalend#90]
Hello.
Please, help me.

Kalend is not showing properly.
![image](https://user-images.githubusercontent.com/44396377/148438259-6f930b85-534b-4d18-9944-5b26e8dd3b3a.png)

I use bootstrap and react in my application.
Can this be a possible cause of some hypothetical clash between the .css files and the styles for Kalend?

I appreciate your help very much.

Kalend here is used as it is without any fancy stuff added to it. (not even an event)

**Comment by nibdo** [comment]
Hello, please refer to the solution in this issue https://github.com/nibdo/kalend/issues/84 

Problem is probably, that your parent component, where Kalend is placed, does not have height. So Kalend cannot load content (It is needed for correct layout calculations). 

Let me know if it worked

**Comment by slawomirdur** [comment]
Thank you for your support.
I have already read that post and tried out to give height to the parent
component but it did not work out well. The parent component actually
became bigger but the calendar was still not visible. Actually, it made no
difference.

czw., 6 sty 2022, 21:59 użytkownik nibdo ***@***.***> napisał:

**Comment by nibdo** [comment]
Hmm, that is strange then. I can only suggest you can share me screenshot of parent element structure (with styles) from browser dev tools, so I can check it.

I don't think this could be caused by conflicting class names as those in Kalend have prefix. 

Is class ```Kalend__Calendar__root``` expanded over whole parent component when you adjusted height? There might be something different why Kalend is not inheriting height and not expanding.

**Comment by nibdo** [comment]
Hi, I have adjusted some settings, which could possibly fix this issue in version 0.6.5.

**Comment by slawomirdur** [comment]
Hi. Great thanks for your devoted support. I will try it out and notify.

For the time being, I have developed my own version of a simplified
calendar. Should be alright for the purpose.

sob., 8 sty 2022, 14:52 użytkownik nibdo ***@***.***> napisał:
