### ISSUE TITLE
Kalend not showing events

### ISSUE THREAD

**Issue by alexandergurkovdev** [nibdo/kalend#92]
I transform my data to this form and transfer it to kalend, but it does not render anything
`
{
    "07-01-2022": [
        {
            "id": 2,
            "startAt": "2022-01-07T11:44:18.051Z",
            "endAt": "2022-01-31T11:44:21.051Z",
            "summary": "День Рождения компании",
            "color": "blue",
            "calendarID": "work"
        },
        {
            "id": 7,
            "startAt": "2022-01-07T13:31:57.313Z",
            "endAt": "2022-01-08T14:32:01.313Z",
            "summary": "test 5",
            "color": "blue",
            "calendarID": "work"
        },
        {
            "id": 5,
            "startAt": "2022-01-07T15:31:24.882Z",
            "endAt": "2022-01-07T17:00:00.030Z",
            "summary": "test 3",
            "color": "blue",
            "calendarID": "work"
        },
        {
            "id": 6,
            "startAt": "2022-01-07T18:34:39.830Z",
            "endAt": "2022-01-07T20:02:00.212Z",
            "summary": "test 4",
            "color": "blue",
            "calendarID": "work"
        },
        {
            "id": 8,
            "startAt": "2022-01-07T15:32:13.579Z",
            "endAt": "2022-01-07T16:00:00.832Z",
            "summary": "test 6",
            "color": "blue",
            "calendarID": "work"
        }
    ],
    "08-01-2022": [
        {
            "id": 3,
            "startAt": "2022-01-08T17:55:52.159Z",
            "endAt": "2022-01-09T17:55:55.159Z",
            "summary": "test 1",
            "color": "blue",
            "calendarID": "work"
        }
    ],
    "06-01-2022": [
        {
            "id": 4,
            "startAt": "2022-01-06T17:59:07.203Z",
            "endAt": "2022-01-06T19:00:00.462Z",
            "summary": "test 2",
            "color": "blue",
            "calendarID": "work"
        }
    ]
}
`

**Comment by alexandergurkovdev** [comment]
![image](https://user-images.githubusercontent.com/49961947/148638556-acd222ff-19c1-4510-9c34-c702cdb9057d.png)
at the same time, the same data in the storybook is rendered normally

**Comment by nibdo** [comment]
Did you resolve this?

**Comment by alexandergurkovdev** [comment]
> Did you resolve this?

Yes. I used incorrect date format for Event item
