### ISSUE TITLE
render Kalend in Accordion

### ISSUE THREAD

**Issue by karankumar89** [nibdo/kalend#96]
One of the issues that I am facing is when trying to render Kalend in an accordion that is not active, it doesnt render since the height or flex basis is 0. I would like Kalend to grow or stretch when the accordian is set to active

**Comment by nibdo** [comment]
Hi,

in this case it might be necessary to use fixed height for wrapper element around Kalend. I tried mui accordion and it rendered after expanding accordion. But I don't know, if fixed height is usable for you. 

![accordion](https://user-images.githubusercontent.com/57879411/149683485-a0cbeadd-a54a-464d-94df-89d931de967c.png)

**Comment by karankumar89** [comment]
Thanks for the quick response. I'm using react-bootstrap accordion and it doesnt render even by giving the height to parent
https://codesandbox.io/s/nifty-herschel-zvrky?file=/src/App.js

**Comment by nibdo** [comment]
Thank you for example. I played with it little bit and Kalend is in this case mounted before you open accordion item, therefore it has 0 height until you resize browser window. I tried few listeners to internal wrapper, but with no success.

However you can solve this for now with conditional loading for Kalend, so it won't be rendered until you expand accordion item. You will still have to set fixed height.

See example here: https://codesandbox.io/s/billowing-fire-m0qum?file=/src/App.js 

I might add conditional option inside app, but it would server same purpose. But some basic settings like minHeight or isLoaded might be added in the future make it easier. Right now I don't know how to better distribute calendar layout for different use cases, but there might be some way.

**Comment by karankumar89** [comment]
Thanks for the suggestion. I did a conditional rendering when the accordion state is set and it works :)

**Comment by nibdo** [comment]
Good to hear :)
